Modification of section data, creating new symbols, other improvements
david942j/rbelftools pull request #52
Opened 2021-03-31 06:30 UTC by zygzagZ

Hello
I've had a college project where I have benefitted from your library, though I have quickly realised it was not going to be enough.
These changes are just as I have sent the project in yesterday and they still lack a bit of refinement, I am going to refactor it.

I ran the tests and they passed, but the functionality implemented in this PR was only tested on ET_REL linker object files and lacks tests.

Summary:
- allow preloading of data (build all structures in memory)
- allow modification and rebuilding ELF files – adding, deleting, reordering sections, symbols, relocations
- fixed a bug where elf header's `e_ident`'s attributes cannot be written, as they cannot be packed into int by the bindata patches-gathering monkeypatch

Implementation decisions:
- no idea what is LazyArray for, will try to get rid of it in refactor and still achieve lazy loading (even though the whole elf is loaded into memory when saving)
- created new Enums that are a bit better, but also bad. Needs some thinking
- properly splitting the functionality of appending symbols requires classes to have access to relative parent (eg. `Relocation` to a `RelocationSection` and `RelocationSection` to an `ELFFile`), things get complicated because this causes loops that break `loaded_headers`. Worked around it with lambdas containing variables, but might consider appending loaded headers to some elffile internal set structure (thus fixing "bad idea..." loaded headers behavior)

Please do not hesitate to comment in case you spot anything i forgot to mention and that would need fixing in the code.

2021-04-02 20:27 UTC, zygzagZ commented
Code cleaned up, rubocop passes and so do tests. Fails on coverage because of the tool crashing (?), no idea how to fix that

Introduced methods still lack comments and documentation.

2021-04-03 05:42 UTC, david942j commented
Hi @zygzagZ, thanks for your contributing! The overall idea looks good, but I need you to perform some changes.

First of all, as I can see you are trying to achieve a lot of changes in one PR, I would prefer to separate them to multiple pull requests. Currently this PR is too large that I'm not able to see what's the purpose of each change (because there are too many purposes). A quick glance shows this PR can be separated to at least 5 PRs:
1. The ability of modifying sections
2. Introducing Enum (I didn't think why adding this could make what better, you can add more details when creating this PR)
3. Modification of lazy_array.rb
4. Modification of CHOICE_SIZE_T
5. Bug fix per your PR description

The test failure of posting code coverage is an infra issue, you can ignore them.

Also please add tests when adding new features and keep the test coverage being 100%.

2021-04-03 05:43 UTC, david942j requested changes

2021-04-03 05:43 UTC, david942j commented on lib/elftools/constants.rb
> +      SHF_MASKPROC = 0xf0000000	# Processor-specific
replace with one space `0xf0000000 #`

2021-04-03 05:43 UTC, david942j commented on lib/elftools/constants.rb
> +    # Section header types, records in +sh_type+.
replace with proper description

2021-04-03 05:43 UTC, david942j commented on lib/elftools/elf_file.rb
>        @sections[n]
suggest
`@sections[n].tap { |sec| sec.index = n if sec }`

2021-04-03 05:43 UTC, david942j commented on lib/elftools/elf_file.rb
> +    def rebuild
add description on what does this function do and what it returns

2021-04-03 05:43 UTC, david942j commented on lib/elftools/elf_file.rb
> +          # align with 0 bytes
null bytes

2021-04-03 05:43 UTC, david942j commented on lib/elftools/elf_file.rb
> +        sh = s.header.to_binary_s
variable `sh` can be omitted

2021-04-03 05:43 UTC, david942j commented on lib/elftools/elf_file.rb
> +      all[0...header.num_bytes] = header.to_binary_s
add a comment about why this line is needed (something like "fields of `header` were changed ... ")

2021-04-03 05:43 UTC, david942j commented on lib/elftools/elf_file.rb
> +    def append_symbol(*args, **kwargs)
add descriptions

2021-04-03 05:43 UTC, david942j commented on lib/elftools/elf_file.rb
> +    def append_section(name, type)
add descriptions

2021-04-03 08:03 UTC, zygzagZ commented on lib/elftools/elf_file.rb
> +          # align with 0 bytes
could you elaborate?

2021-04-03 09:56 UTC, zygzagZ commented
The purpose of Enum was to make it possible to add wrapper methods to Symbol, Section that return header's data in more verbose way.
I wanted to enable usage as such:
```
sym = elf.symtab.symbol_by_name('puts@@GLIBC_2.0')
puts sym.st_type
> "FUNC"
puts "it is a function!" if sym.st_type.func?
sym.st_vis = Visibility.PROTECTED
``
that allows easier debugging without the need of custom functions like `Constants::ET.mapping`.
It is not perfect though, would be nice have const access `Visibility::PROTECTED` or something like `sym.st_vis = :protected`, but did not yet implement this.

2021-04-21 12:45 UTC, david942j commented
Hi @zygzagZ , do you have plan to separate your PR to several smaller ones as my previous suggestion?

2021-04-21 15:12 UTC, zygzagZ commented
I do, just can't get around to it.
Any tips what would make the least laborious way to achieve it? Is there a tool such that I can decide whether to keep or discard each line of a diff (so as to split it between branches)?

2021-04-22 23:43 UTC, david942j commented
Sounds like you need `git add -p` ?

2021-05-05 20:54 UTC, zygzagZ commented
superseded by #58 #59 #60 #61 #62 #63 #64.
Hope that nothing falls apart and that I did not miss anything.

2021-05-05 20:54 UTC, closed without merging