More DRY structs, CHOICE_SIZE_T as proc
david942j/rbelftools pull request #59
Opened 2021-05-05 20:29 UTC by zygzagZ

Also, added r_addend reader for ELF_Rel for easier use

Part of #52

2021-05-05 20:58 UTC, zygzagZ commented
Oh yeah, rubymine warned me that the "redundant begin block" is required before ruby 2.5, as that is apparently ruby version where syntax 
```
do |sth|
  puts 'ayy'
rescue Exception => e
  puts 'rescued'
end
```
was introduced?

gemspec lists 2.4 support, so I decided to refactor into begin/rescue/end block

2021-05-07 14:05 UTC, david942j requested changes

2021-05-07 14:05 UTC, david942j commented on lib/elftools/structs.rb
> +      def r_addend
add a simple comment about why define this

2021-05-07 17:49 UTC, zygzagZ commented
Fixed

2021-05-08 06:02 UTC, merged