Enums
david942j/rbelftools pull request #62
Opened 2021-05-05 20:45 UTC by zygzagZ

I do not consider this part of code perfect, yet this is what I came up with to manage elf types more easily. 

I think constants should be accessed with Class::CONSTANT, eg. `Visibility::NONE`, yet these enums currently work only with 
`Visibility.NONE`. I did not fix it, I was short on time. I also don't see clear solution.

What I wanted from these enums:
- fiddle with easily in byebug, cast to string: `puts symbol.st_vis` to print `None` instead of  ... 42 or whatever. 
- use in expressions just as constants before: `symbol.st_vis + 2` to be 44 (or whatever) instead of "None2", currently may require casting with `.to_i`
- allow assigning with symbol `symbol.st_vis = :none`, dunno if works

Part of #52

2021-05-08 13:42 UTC, david942j requested changes

2021-05-08 13:42 UTC, david942j commented on lib/elftools/enums.rb
> +    attr_reader :values
add document of its type

2021-05-08 13:42 UTC, david942j commented on lib/elftools/enums.rb
> +    def val(value)
add document

2021-05-08 13:42 UTC, david942j commented on lib/elftools/enums.rb
> +            elsif values.keys.include?(value)
keys.include? can be replaced with "key?"

2021-05-08 13:42 UTC, david942j commented on lib/elftools/enums.rb
> +    v ? "#{self.class.name}.#{v.upcase}" : @value
unsure whether it matters - shouldn't "@value" be "@value.inspect"?

2021-06-24 13:44 UTC, david942j commented
Any update here :) ?

2021-07-24 14:37 UTC, david942j commented
yes?

2021-07-24 14:40 UTC, zygzagZ commented
Sorry, will do, got small setback and had little time

On Sat, Jul 24, 2021, 16:37 david942j ***@***.***> wrote:

> yes?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/david942j/rbelftools/pull/62#issuecomment-886062197>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABWONCR3HU6UTDXWRFZCNQ3TZLFZ3ANCNFSM44FXJORQ>
> .
>

2026-08-25 00:32 UTC, david942j commented
Closing this PR due to no activities and the functionalities it attempting to ship was already covered.

For the record, #89 added `Symbol#type`, `#bind`, `#visibility`, and `#section_index`,
and #101 added `#type_name`, `#bind_name`, and `#visibility_name`. Relocation types
came in #93 and #95. Those are generated from binutils.

#112 added `Symbol#type=`, `#bind=`, `#visibility=`, and
`Relocation#type=` and `#symbol_index=`, which was the genuinely missing half and the
part of this PR I kept. They are built on `Constants::STT`/`STB`/`STV`/`R` rather
than a parallel enum class, they preserve what shares the byte or field.

Closing as superseded by those. Thanks for pushing on the idea.

2026-08-25 00:32 UTC, closed without merging